<div class='bankbox box'>		
	<h3>Půjčka</h3>					
	<form method='post'>
		Operace:
		<select name='operace'>							
			<option value='vrat' selected='selected'>Vrátit</option>
			<option value='pujc'>Půjčit</option>
		</select>
		Částka:
		<select name='castka'>
			<option value='5000'  selected='selected'>5 000</option>
			<option value='10000'>10 000</option>
			<option value='20000'>20 000</option>
			<option value='50000'>50 000</option>
			<option value='100000'>100 000</option>
		</select>
			<input type='submit' value='Proveď'>
		</form>
</div>
