<li>
  <img style="padding:5px;" src='./graphics/mini-icons/nation.png'/><h4><a href="./index.php?pid=natdetail&id={$id}">{$nazev}</a></h4>
  <h5>(</h5><img class="medium" src='./graphics/mini-icons/vladce.png'/><h5>{$majitel})</h5>
  
  <div class="right">
    <img class="minimal" src='./graphics/mini-icons/penize.png'/><h5>$ {$penize}</h5><br>
    <img class="minimal" src='./graphics/mini-icons/population.png'/><h5>{$clenu}</h5>
  </div>
</li>