<ul id="tutorial">
			<li>Jakékoli použití za účelem výdělku nebo pro komerční účely je zakázáno</li>
			<li>Uživatel je povinen uchovávat své přihlašovací údaje a všechna hesla a identifikační údaje v přísném utajení. </li>
			<li>Uživatel je povinen chránit přihlašovací údaje, identifikační údaje a hesla před neoprávněným přístupem třetích stran.</li>
			<li>Uživateli jsou zakázány jakékoli formy manipulativních zásahů do online hry. Zejména není uživatel oprávněn používat opatření, zařízení nebo software, který by mohl narušit funkčnost nebo průběh hry. Uživatel nesmí vykonávat žádná opatření, která by měla za následek nepřiměřené nebo nadměrné zatížení technických zařízení. Uživateli není dovoleno blokovat, přepisovat nebo upravovat obsahy, které generuje administrace hry, nebo jakýmkoli jiným způsobem do hry zasahovat.</li>
			<li>Uživatel je oprávněn vlastnit pouze jeden herní účet</li>
			<li>Uživateli je zakázáno spouštět online hru jinými programy, než jsou internetové prohlížeče. To se týká zejména takzvaných botů a jiných nástrojů, které by mohly nahrazovat nebo doplňovat internetové rozhraní. Rovněž jsou zakázány skripty a zcela nebo částečně automatizované programy, které uživateli zajišťují výhodu nad ostatními spoluhráči.</li>
			<li>Uživatel je povinen se v diskusích vyjadřovat slušně a s respektem k ostatním zůčastněěným a diskutujícím.</li>
			<li>V rámci statistických analýz sbíráme v některých oblastech našich internetových služeb údaje, jako je třeba operační systém a jeho verze, prohlížeč a jeho verze, IP adresa a také další systémové údaje. Tyto údaje využíváme pro statistické analýzy, zejména za účelem přizpůsobení našich internetových služeb potřebám uživatelů. Pokud je to možné, jsou takto získané údaje anonymizovány. Žádná údaje navíc nejsou předávány třetím stranám.</li>
			<li>Provozovatel se zříká zodpovědnosti za ztrátu jakýchkoliv dat uživatelů</li>
</ul>
