<div id="leftpanel">
				<p>Veškeré novinky a informace o updatech naleznete v našem <a href="./forum/showthread.php?topicid=16">fóru</a></p>
				<hr>
				<p>Založte si účet a hned začněte hrát</p><button><a href="./registrace.php">Registrovat</a></button>
				<hr>
				
				<p>Vývoj hry můžete finančně podpořit pomocí tohoto odkazu</p>
				<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" id="donate">
					<input type="hidden" name="cmd" value="_s-xclick">
					<input type="hidden" name="hosted_button_id" value="YTFVMFGM53S3E">
					<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
					<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
				</form>
			</div>
			
			
			<div class="tip">
				<img src="./graphics/ind3.png" alt="náhled" width="220">
				<p>Můžete vyzkoušet své štěstí v loterii, a pokusit se tak vylepšit svůj rozpočet</p>
			</div>
			
			<div class="tip">
				<img src="./graphics/ind1.png" alt="náhled" width="220">
				<p>Poradce vám napoví co děláte špatně, a jak můžete zvýšit zisky svého ostrova</p>
			</div>
			
			<div class="tip">
				<img src="./graphics/ind2.png" alt="náhled" width="380">
				<p style="width:300px;">Vybudujte si ostrov přesně podle vašich představ a staňte se jeho starostou.Je jen na vás jakou strategii zvolíte, a kolik peněz si vyděláte.</p>
			</div>
			
			{$bannery}
			
	<div style="clear: left;"></div>
