<div id="leftpanel">
				<p>Veškeré novinky a informace o updatech naleznete v našem <a href="./forum/showthread.php?topicid=16">fóru</a></p>
				<hr>
				<p>Založte si účet a hned začněte hrát</p><button><a href="./registrace.php">Registrovat</a></button>
				<hr>
				<img src="http://img19.imageshack.us/img19/1060/48mz.jpg" alt="centrum">
				<img src="http://imageshack.us/a/img811/752/3qcz.jpg" alt="Náhled">
				<img src="http://img827.imageshack.us/img827/8894/2e13.jpg" alt="chatky">
				<img src="http://imageshack.us/a/img96/1413/mobx.jpg" alt="Přístav">
			</div>
			
			
			<div class="tip">
				<img src="./graphics/ind3.png" alt="náhled" width="220">
				<p>Můžete vyzkoušet své štěstí v loterii, a pokusit se tak vylepšit svůj rozpočet</p>
			</div>
			
			<div class="tip">
				<img src="./graphics/ind1.png" alt="náhled" width="220">
				<p>Poradce vám napoví co děláte špatně, a jak můžete zvýšit zisky svého ostrova</p>
			</div>
			
			<div class="tip">
				<img src="./graphics/ind2.png" alt="náhled" width="380">
				<p style="width:300px;">Vybudujte si ostrov přesně podle vašich představ a staňte se jeho starostou.Je jen na vás jakou strategii zvolíte, a kolik peněz si vyděláte.</p>
			</div>
			
			{$bannery}
			
	<div style="clear: left;"></div>
