<ul id="tutorial">
		<li>Idélní daně pro váš ostrov by měly být mezi 17-19</li>
		<li>Při příliš vysokých daních budou váš ostrov lidé opouštět</li>
		<li>Pro vyšší spokojenost obyvatel můžete vystavět zábavní průmysl</li>
		<li>Pokud bude na ostrově dostatek nemocnic, vaše oblíbenost poroste</li>
		<li>Pokud bude město zásobené elektřinou, oblíbenost vzroste</li>
		<li>Při větším množství továren bude vaše oblíbenost klesat</li>
	<li>Je třeba udržovat počet ubytovacích míst a přepravní kapacitu přibližně na stejné hodnotě, jinak bude jeden ze segmentů prodělávat</li>
	<li>Vytěžené suroviny můžete prodat do obchodu a vydělat si tak další peníze</li>
	<li>Na některé nedostatky ostrova vás upozorní poradce kterého najdete v Bance</li>
</ul>
